# Generated by Django 3.2.7 on 2021-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_tasklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
